theme: jekyll-theme-cayman
title: "Artyom Yagovdik"
seo_tag:
  title: false
description: "Senior Full-Stack Developer"
google_analytics: "UA-170843825-1"
linkedin_url: "https://www.linkedin.com/in/artyom-yagovdik/"
github_url: "https://github.com/artttj"
markdown: CommonMarkGhPages
