theme: jekyll-theme-cayman
title: [Artyom Yagovdik]
description: [Software Developer]
google_analytics: "UA-170843825-1"
linkedin_url: "https://www.linkedin.com/in/artyom-yagovdik/"
github_url: "https://github.com/artttj"